using System.Collections.ObjectModel;
namespace GameshowPro.Common.Model.Lights;

public abstract class FixturesBase<TSub> : KeyedCollection<string, Fixture>
    where TSub : FixturesBase<TSub>, new()
{
    protected static void Persist(IPersistence persistence, TSub lights, IList<StatePresetGroup>? presetGroup, string? lightsPath, string? presetsPath)
    {
        persistence.Persist(lights.Select(FixtureSettings.FromFixture), lightsPath, true);
        persistence.Persist(presetGroup, presetsPath, true);
    }

    protected static TSub Depersist(IPersistence persistence, string? lightsPath, string? presetsPath, ILogger logger)
    {
        List<FixtureSettings> depersistedSettings = persistence.Depersist<List<FixtureSettings>>(lightsPath, out _);
        StatePresetGroups depersistedGroups = persistence.Depersist<StatePresetGroups>(presetsPath, out _);
        TSub newFixtures = new();
        newFixtures.Create(depersistedGroups, depersistedSettings, logger);
        return newFixtures;
    }

    /// <summary>
    /// Update the current instance for consistency with the template generated by the subclass.
    /// </summary>
    private void Create(StatePresetGroups depersistedGroups, List<FixtureSettings> depersistedSettings, ILogger logger)
    {
        IEnumerable<StatePresetGroup> defaultPresetGroups = BuildPresetGroups();
        _presetGroups = depersistedGroups;
        SyncPresetGroups(ref _presetGroups, defaultPresetGroups);
        _presetGroups.AddChannelTypes();
        bool startIdsAreInvalid = this.Count(f => f.StartId == 0) > 1;
        IEnumerable<Fixture> template = BuildTemplate(_presetGroups);
        Dictionary<string, FixtureSettings> settings = SettingsToDictionary(depersistedSettings, logger);
        foreach (Fixture templateFixture in template)
        {
            if (settings.TryGetValue(templateFixture.Key, out FixtureSettings? fixtureSettings))
            {
                fixtureSettings.ToFixture(templateFixture);
            }
            Add(templateFixture);
            SetChannelParents(this[templateFixture.Key]);
        }
    }

    private static Dictionary<string, FixtureSettings> SettingsToDictionary(List<FixtureSettings> depersistedSettings, ILogger logger)
    {
        Dictionary<string, FixtureSettings> dict = [];
        foreach (FixtureSettings fs in depersistedSettings)
        {
            if (!dict.TryAdd(fs.Key, fs))
            {
                logger.LogError("Multiple fixture settings were found with the key {key}", fs.Key);
            }
        }
        return dict;
    }


    private static void SetChannelParents(Fixture fixture)
    {
        foreach (FixtureChannel channel in fixture.Channels)
        {
            channel.Parent = fixture;
        }
    }

    /// <summary>
    /// Ensure that the depersisted data contains all groups which exist in the defaults
    /// </summary>
    /// <param name="depersisted"></param>
    /// <param name="defaults"></param>
    private static void SyncPresetGroups(ref StatePresetGroups depersisted, IEnumerable<StatePresetGroup> defaults)
    {
        //Note - it probably would have been smarter just copy the values from each depersisted group into its
        //corresponding default, then use the modified default instead.
        Dictionary<StatePresetGroup, StatePresetGroup> depersistedToDefault = [];
        foreach (StatePresetGroup defG in defaults)
        {
            if (depersisted.Contains(defG.Name))
            {
                //Already exists, so look deeper
                StatePresetGroup depG = depersisted[defG.Name];

                depersistedToDefault.Add(depG, defG);
                for (var i = depG.StatesLevels.Count - 1; i >= 0; i--)
                {
                    if (string.IsNullOrWhiteSpace(depG.StatesLevels[i].Key))
                    {
                        depG.StatesLevels.RemoveAt(i);
                    }
                }

                foreach (StateLevels defLevels in defG.StatesLevels)
                {
                    if (!depG.StatesLevels.Contains(defLevels.Key))
                    {
                        depG.StatesLevels.Add(defLevels);
                    }
                }

                if (depG.ChannelColors.Count != defG.ChannelColors.Count)
                {
                    depG.ChannelColors = defG.ChannelColors;
                }
            }
            else
            {
                //Doesn't exist at all, so take whole of default
                depersisted.Add(defG);
                depersistedToDefault.Add(defG, defG);
            }
        }
        List<string> groupsToRemove = [];
        foreach (StatePresetGroup depG in depersisted)
        {
            if (depersistedToDefault.TryGetValue(depG, out StatePresetGroup? value))
            {
                List<string> levelsToRemove = depG.StatesLevels.Where(depL => !value.StatesLevels.Contains(depL.Key)).Select(depL => depL.Key).ToList();
                foreach (string key in levelsToRemove)
                {
                    //Depersisted state levels has a key that does not exist in corresponding group in default template
                    depG.StatesLevels.Remove(key);
                }
            }
            else
            {
                groupsToRemove.Add(depG.Name);
            }
        }
        foreach (string key in groupsToRemove)
        {
            //Depersisted group has a key that does not exist in default template
            _ = depersisted.Remove(key);
        }
    }

    protected static List<FixtureChannel> ChannelsFromPreset(StatePresetGroup? presetGroup)
        => presetGroup is null ? new() : new(Enumerable.Range(0, presetGroup.ChannelColors.Count).Select(
            i =>
            new FixtureChannel(presetGroup.ChannelColors[i])
        ).ToList());

    protected abstract IEnumerable<Fixture> BuildTemplate(IEnumerable<StatePresetGroup> presetGroups);
    protected abstract IEnumerable<StatePresetGroup> BuildPresetGroups();

    private StatePresetGroups? _presetGroups;
    public StatePresetGroups? PresetGroups
    {
        get
        {
            return _presetGroups;
        }
        set
        {
            if (_presetGroups != null)
            {
                throw new InvalidOperationException($"Once {nameof(PresetGroups)} is set, it is immutable.");
            }
            _presetGroups = value;
        }
    }

    protected override string GetKeyForItem(Fixture item)
    {
        return item.Key;
    }
}
