global using static Barjonas.Common.Utils;
global using static Barjonas.Common.UtilsWindows;
global using System;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Configuration;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Reflection;
global using System.Windows;
global using System.Windows.Threading;
global using System.Data;
global using System.Collections;
global using System.ComponentModel;
global using NLog;
global using Newtonsoft.Json;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Input;
global using Microsoft.Xaml.Behaviors;
global using System.Drawing;
global using System.IO;
global using System.Security.Principal;
global using Barjonas.Common.Model;
global using Microsoft.WindowsAPICodePack.Dialogs;
